fix ESCAPE_RE regular expression
swistakm/solrq pull request #3
Opened 2017-02-09 20:10 UTC by cormier

Make it match a single backslash character. Test that it matches a
single backslash. Remove Proximity(Value()): they cannot be equal,
because the space will be escaped in the instanciation of Value, and the
backslash used to escape the space will then be escaped in Proximity.

2017-02-09 22:20 UTC, swistakm requested changes
Thanks! Only two minor code style issues.

2017-02-09 22:20 UTC, swistakm commented on tests/test_squery.py
Add additional new line to satisfy pep8 checks

2017-02-09 22:20 UTC, swistakm commented on tests/test_squery.py
Add additional new line to satisfy pep8 checks

2017-02-10 14:39 UTC, cormier commented
Thanks for the review. I updated my branch.

2017-02-10 23:15 UTC, merged

2017-02-10 23:16 UTC, swistakm commented
Thanks! I will create new realease in the beginning of the next week when I resolve pypy build issue on travis.

2017-03-05 15:51 UTC, swistakm commented
Released as `1.1.1`. Sorry it took so long.